---
- name: Ensure Skeleton service is configured
  when: skeleton_service_update or not skeleton_service_exists
  block:
    - name: Copy Skeleton daemon config into place
      become: true
      ansible.builtin.template:
        src: skeleton.service.j2
        dest: "{{ skeleton_service_path }}"
        owner: root
        group: root
        mode: "0644"
        force: "{{ skeleton_service_update or ansible_local.skeleton is undefined }}"

    - name: Systemd daemon-reload
      become: true
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Ensure service is started
      become: true
      ansible.builtin.service:
        name: "{{ skeleton_daemon }}"
        state: "{{ skeleton_state }}"
        enabled: "{{ skeleton_enabled_on_boot }}"
