---
- name: Include OS-specific variables ({{ ansible_os_family }})
  ansible.builtin.include_vars:
    dir: vars
    files_matching: "{{ item }}"
    depth: 1
  loop:
    - "all.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  failed_when: false

- name: Check if Docker is already installed
  vars:
    docker_paths:
      - name: config
        path: "{{ docker_config_path }}"
  block:
    - name: Find existing Docker files
      ansible.builtin.stat:
        path: "{{ item.path }}"
      loop: "{{ docker_paths }}"
      register: docker_files

    - name: Register existing Docker files
      ansible.builtin.set_fact:
        "docker_{{ item.item.name }}_exists": "{{ item.stat.exists }}"
      loop: "{{ docker_files.results }}"
