---
- name: Ensure Skeleton database is configured
  become: true
  community.mysql.mysql_db:
    name: "{{ skeleton_mysql_database }}"
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    state: present

- name: Ensure Skeleton database user exists
  become: true
  community.mysql.mysql_user:
    name: "{{ skeleton_mysql_database_user }}"
    host: localhost
    password: "{{ skeleton_mysql_database_user_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    priv: skeleton.*:ALL
    state: present
  no_log: "{{ skeleton_hide_passwords }}"
