---
- name: Add Skeleton definition in Caddy configuration
  become: true
  ansible.builtin.template:
    src: caddy/skeleton.site.j2
    dest: "{{ caddy_config_dir_sites | default(ansible_local.caddy.dirs.sites) }}/skeleton.site"
    owner: root
    group: root
    mode: "0644"
    force: true
  notify: Reload reverseproxy

- name: Add Skeleton route in Caddy configuration
  become: true
  ansible.builtin.template:
    src: caddy/skeleton.route.j2
    dest: "{{ caddy_config_dir_sites | default(ansible_local.caddy.dirs.sites) }}/skeleton.route"
    owner: root
    group: root
    mode: "0644"
    force: true
  notify: Reload reverseproxy
